"""Add category field to Nft model

Revision ID: c11d32ff2413
Revises: dcd90c0cfd6f
Create Date: 2022-05-19 07:23:08.213476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11d32ff2413'
down_revision = 'dcd90c0cfd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nft', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nft', 'category')
    # ### end Alembic commands ###
